import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Intro from "../components/Intro";
import Services from "../components/Services";
import Testmonials from "../components/Testmonials";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Intro />
      <Services />
      <Testmonials />
    </div>
  );
}

// export const getStaticProps = async () => {
//   const services = data;
//   return {
//     props:{services}
//   };
// };
